myAge=20
myScore=80.5
isLogin=True
mySigal=3+2j
print(myAge,type(myAge))
print(myScore,type(myScore))
print(isLogin,type(isLogin))
print(mySigal,type(mySigal))
# 字符串换行
myAddr='''北京
假按揭啊'''
print(myAddr,type(myAddr))
#元组一个数据后面跟逗号，不然是int
myTuple=(40,)
#字典
myDict={
  'age':20,
  'name':'dingding'
}
print(myDict,type(myDict))
